"""Persistence port interfaces for application layer."""

from __future__ import annotations

from collections.abc import Sequence
from datetime import datetime
from typing import Any, Protocol

from app.domain.ordering import Order as DomainOrder


class BrandRepositoryPort(Protocol):
    async def get_by_id(self, id: int) -> Any | None: ...
    async def get_all(self, skip: int = 0, limit: int = 100) -> Sequence[Any]: ...
    async def create(self, **kwargs: object) -> Any: ...
    async def update(self, id: int, **kwargs: object) -> Any | None: ...
    async def delete(self, id: int) -> bool: ...


class CatalogRepositoryPort(Protocol):
    async def get_by_id(self, id: int) -> Any | None: ...
    async def get_all(self, skip: int = 0, limit: int = 100) -> Sequence[Any]: ...
    async def create(self, **kwargs: object) -> Any: ...
    async def update(self, id: int, **kwargs: object) -> Any | None: ...
    async def delete(self, id: int) -> bool: ...


class CustomerRepositoryPort(Protocol):
    async def get_by_id(self, id: int) -> Any | None: ...
    async def get_all(self, skip: int = 0, limit: int = 100) -> Sequence[Any]: ...
    async def create(self, **kwargs: object) -> Any: ...
    async def update(self, id: int, **kwargs: object) -> Any | None: ...
    async def delete(self, id: int) -> bool: ...
    async def email_exists(self, email: str, exclude_id: int | None = None) -> bool: ...


class ProductRepositoryPort(Protocol):
    async def get_by_id(self, id: int) -> Any | None: ...
    async def get_all(self, skip: int = 0, limit: int = 100) -> Sequence[Any]: ...
    async def create(self, **kwargs: object) -> Any: ...
    async def update(self, id: int, **kwargs: object) -> Any | None: ...
    async def delete(self, id: int) -> bool: ...
    async def sku_exists(self, sku: str, exclude_id: int | None = None) -> bool: ...


class OrderRepositoryPort(Protocol):
    async def get_by_id(self, id: int) -> Any | None: ...
    async def get_all(self, skip: int = 0, limit: int = 100) -> list[Any]: ...
    async def get_by_customer_id(self, customer_id: int, skip: int = 0, limit: int = 100) -> list[Any]: ...
    async def create_from_aggregate(self, aggregate: DomainOrder) -> Any: ...
    async def update(self, id: int, **kwargs: object) -> Any | None: ...


class OrderItemRepositoryPort(Protocol):
    async def get_by_order_id(self, order_id: int) -> list[Any]: ...


class InventoryReservationRepositoryPort(Protocol):
    async def create(self, **kwargs: object) -> Any: ...
    async def get_by_id(self, id: int) -> Any | None: ...
    async def get_held_by_order(self, order_id: int) -> list[Any]: ...
    async def get_expired_holds(self) -> list[Any]: ...


class PromotionRepositoryPort(Protocol):
    async def create(self, **kwargs: object) -> Any: ...
    async def get_all(self, skip: int = 0, limit: int = 100) -> Sequence[Any]: ...
    async def get_by_id(self, id: int) -> Any | None: ...
    async def update(self, id: int, **kwargs: object) -> Any | None: ...
    async def delete(self, id: int) -> bool: ...
    async def get_active(self, now: datetime) -> list[Any]: ...
